%%{init: { 'logLevel': 'debug', 'theme': 'neutral' } }%%

sequenceDiagram
    autonumber
    actor C as Cliente
    participant S as Servidor <br/> FTCP

    %% Etapa 1 – Negociação Inicial via UDP
    C->>S: UDP: REQUEST,<PROTOCOLO>,<ARQUIVO> (ex.: a.txt ou b.txt)
    S->>S: Verifica a configuração
    S-->>C: UDP: RESPONSE:<TRANSFER_PORT>,<ARQUIVO>
    
    %% Etapa 2 – Transferência do Arquivo (dividida em TCP e UDP)
    alt Transferência via TCP
        C->>S: TCP: Conecta na porta <TRANSFER_PORT> (TCP_A_PORT ou TCP_B_PORT)
        C->>S: TCP: Envia confirmação da solicitação (nome do arquivo)
        loop Envio dos Segmentos
            S->>C: TCP: Envia segmento
            C->>S: TCP: Envia ACK para o segmento recebido
        end
    else Transferência via UDP
        C->>C: Prepara para receber pacotes na porta <TRANSFER_PORT> (UDP_PORT)
        loop Envio dos Segmentos (sem confirmação)
            S->>C: UDP: Envia segmento
        end
    end